Repository EspressoSystems/HotShot, pull requests merged in 2023-12, with the labels that each got.

#2149 VID share distribution algorithm
  crates/task-impls/src/vid.rs
  crates/testing/src/task_helpers.rs
  crates/testing/tests/network_task.rs
  crates/testing/tests/vid_task.rs
  crates/types/src/data.rs
Labels: vid

#2244 View Sync Fixes for PreCommit Threshold, Timeout Logic, and Relay Vote Accumulation
  crates/task-impls/src/view_sync.rs
  crates/types/src/simple_certificate.rs
  crates/types/src/vote.rs
Labels: bug, stability

#2261 [Stability] Quick fix for Libp2p CI
  crates/testing/tests/libp2p.rs
Labels: bug, networking, stability

#2277 [Stability] Fix proposal logic
  crates/task-impls/src/consensus.rs
Labels: bug, stability
